# Generated by Django 5.2.8 on 2025-11-19 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cliente",
            options={"verbose_name": "Cliente", "verbose_name_plural": "Clientes"},
        ),
        migrations.AlterModelOptions(
            name="fornecedor",
            options={
                "verbose_name": "Fornecedor",
                "verbose_name_plural": "Fornecedores",
            },
        ),
        migrations.AlterModelOptions(
            name="produto",
            options={"verbose_name": "Produto", "verbose_name_plural": "Produtos"},
        ),
        migrations.AlterModelOptions(
            name="venda",
            options={"verbose_name": "Venda", "verbose_name_plural": "Vendas"},
        ),
    ]
